site_name: Software Accounting
site_url: https://hpc2n.github.io/softwareaccounting/

repo_name: hpc2n/softwareaccounting
repo_url: https://github.com/hpc2n/softwareaccounting/

theme:
  name: material

nav:
  - Home: index.md
  - Overview: overview.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Logging: logging.md
  - Programs:
    - Aggregator: sams-aggregator.md
    - Collector: sams-collector.md
    - POST Receiver: sams-post-receiver.md
    - Software Extractor: sams-software-extractor.md
    - Software Updater: sams-software-updater.md
  - Modules:
    - sams.aggregator:
      - SoftwareAccounting: aggregator/SoftwareAccounting.md
      - SoftwareAccountingPW: aggregator/SoftwareAccountingPW.md
    - sams.backend:
      - SoftwareAccounting: backend/SoftwareAccounting.md
      - SoftwareAccountingPW: backend/SoftwareAccountingPW.md
    - sams.loader:
      - File: loader/File.md
      - FileSlurmInfoFallback: loader/FileSlurmInfoFallback.md
    - sams.output:
      - File: output/File.md
      - Http: output/Http.md
    - sams.pidfinder:
      - Slurm: pidfinder/Slurm.md
    - sams.sampler:
      - Core: sampler/Core.md
      - FSStats: sampler/FSStats.md
      - IOStats: sampler/IOStats.md
      - NvidiaSMI: sampler/NvidiaSMI.md
      - Pressure: sampler/Pressure.md
      - SlurmCGroup: sampler/SlurmCGroup.md
      - SlurmCGroup2: sampler/SlurmCGroup2.md
      - SlurmInfo: sampler/SlurmInfo.md
      - Software: sampler/Software.md
      - ZFSStats: sampler/ZFSStats.md
    - sams.software:
      - Regexp: software/Regexp.md
  - Software Versions: sams-software.md
  - FAQ: sams-faq.md
  - Release Notes:
    - 1.9: releasenotes/1.9.md
    - 1.8: releasenotes/1.8.md
    - 1.7: releasenotes/1.7.md
    - 1.6: releasenotes/1.6.md
    - 1.5: releasenotes/1.5.md
    - 1.4: releasenotes/1.4.md
    - 1.3: releasenotes/1.3.md
    - 1.2: releasenotes/1.2.md
    - 1.1: releasenotes/1.1.md
    - 1.0: releasenotes/1.0.md
